# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Polybuddies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Polybuddies

  target 'PolybuddiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolybuddiesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'SwiftyJSON'
  pod 'Firebase/Database'
  pod 'FirebaseUI', '~> 1.0'
end
